# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "About"
  url = "#about_session"
  weight = 15

[[main]]
  name = "Presentations"
  url = "#talks"
  weight = 20

[[main]]
  name = "Hands-On"
  url = "#materials"
  weight = 25

[[main]]
  name = "Resources"
  url = "#resources"
  weight = 30

[[main]]
  name = "Further Reading"
  url = "#featured"
  weight = 35

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40
